services:
  auth:
    build: .
    image: irms-fe-auth
    container_name: irms-fe-auth
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - irms_net

networks:
  irms_net:
    name: irms_net
